version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_DB: tinyfarm
      POSTGRES_USERNAME_FILE: /secret/db_username.txt
      POSTGRES_PASSWORD_FILE: /secret/db_password.txt
    secrets:
      - db_username
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tinyfarm_network
  backend:
    build: ../backend
    container_name: backend_prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME_FILE: /secret/db_username.txt
      DB_PASSWORD_FILE: /secret/db_password.txt
    secrets:
      - db_username
      - db_password
    depends_on:
      - postgres
    networks:
      - tinyfarm_network