/*DATABASE CREATION*/
/*INDEPENDENT OF THE TABLES CREATION*/

CREATE DATABASE tinyfarm
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    IS_TEMPLATE = False
    TEMPLATE = template0;

/*CREATE A SCHEMA FOR THE DATABASE*/
CREATE SCHEMA IF NOT EXISTS tinyfarm;

/*SET THE SEARCH PATH TO USE THE TINYFARM SCHEMA*/
SET search_path TO tinyfarm;

/*REVOKE ALL PRIVILEGES ON THE SCHEMA TO PUBLIC*/
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SCHEMA tinyfarm FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE tinyfarm FROM PUBLIC;
