/*DATABASE CREATION*/
/*INDEPENDENT OF THE TABLES CREATION*/

CREATE DATABASE TinyFarm
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    IS_TEMPLATE = False
    TEMPLATE = template0;

/*CREATE A SCHEMA FOR THE DATABASE*/
CREATE SCHEMA IF NOT EXISTS TinyFarm;

/*REVOKE ALL PRIVILEGES ON THE SCHEMA TO PUBLIC*/
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SCHEMA TinyFarm FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE TinyFarm FROM PUBLIC;