/*===========================================*/
/*  CRÉATION DES TABLES - TinyFarm           */
/*===========================================*/

SET search_path TO TinyFarm;

/* Enum types for animal subtypes */
CREATE TYPE chickenTypeEnum AS ENUM ('poussin', 'poule', 'coq');
--CREATE TYPE rabbit_type_enum AS ENUM ('lapereau', 'lapin');

CREATE TABLE IF NOT EXISTS "User"
(
    uID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR(20),
    sexe VARCHAR(20),
    ecus INTEGER,
    level INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Product
(
    productID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description TEXT,
    collection BOOLEAN,
    price FLOAT,
    coef INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Transactions
(
    tID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seller INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    buyer INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    product INTEGER NOT NULL REFERENCES Product(productID) ON DELETE CASCADE ON UPDATE CASCADE,
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prixTotal FLOAT NOT NULL CHECK (prixTotal >= 0),
    dateTransaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (seller != buyer)
);

CREATE TABLE IF NOT EXISTS Stock
(
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES Product(productID) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER DEFAULT 0 CHECK (quantity >= 0),
    PRIMARY KEY (uID, productID)
);

CREATE TABLE IF NOT EXISTS Desktop
(
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES Product(productID) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    PRIMARY KEY (uID, productID)
);

CREATE TABLE IF NOT EXISTS Animal
(
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    aID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    clean BOOLEAN,
    healthy BOOLEAN,
    age INTEGER,
    weight FLOAT,
    aGender BOOL
);

CREATE TABLE IF NOT EXISTS Chicken
(
    aID INTEGER PRIMARY KEY REFERENCES Animal(aID) ON DELETE CASCADE ON UPDATE CASCADE,
    chickenType chickenTypeEnum,
    fasting INTEGER DEFAULT 0
);

-- CREATE TABLE IF NOT EXISTS Rabbit
-- (
--    aID INTEGER PRIMARY KEY REFERENCES Animal(aID) ON DELETE CASCADE ON UPDATE CASCADE,
--     rabbit_type rabbit_type_enum
-- );

CREATE TABLE IF NOT EXISTS Hutch
(
    uID INTEGER PRIMARY KEY REFERENCES User(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    babyRabbit INTEGER NOT NULL >=0 DEFAULT 8,
    smallRabbit INTEGER NOT NULL >=0 DEFAULT 0,
    bigRabbit INTEGER NOT NULL >=0 DEFAULT 0,
    adultRabbitMale INTEGER NOT NULL >=0 DEFAULT 0,
    adultRabbitFemale INTEGER NOT NULL >=0 DEFAULT 0,
    lastMeal DATE NOT NULL DEFAULT CURRENT_DATE,
    lastDrink DATE NOT NULL DEFAULT CURRENT_DATE,
    timeSick DATE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Cow
(
    aID INTEGER PRIMARY KEY REFERENCES Animal(aID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Event
(
    eID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    text VARCHAR(200) NOT NULL,
    dateEvent TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Market
(
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES Product(productID) ON DELETE CASCADE ON UPDATE CASCADE,
    price FLOAT NOT NULL,
    PRIMARY KEY (uID, productID)
);

CREATE TABLE IF NOT EXISTS Cooperative
(
    uID INTEGER NOT NULL REFERENCES "User"(uID) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES Product(productID) ON DELETE CASCADE ON UPDATE CASCADE,
    isOpen BOOLEAN,
    PRIMARY KEY (uID, productID)
);
