/*CREATE THE TABLES HERE*/

CREATE TABLE IF NOT EXISTS Stock
(
    u_id INTEGER REFERENCES NOT NULL (User.id) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER REFERENCES NOT NULL (Product.productID) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER DEFAULT 0 CHECK (quantity >= 0)
    PRIMARY KEY (u_id, productID)
);

CREATE TABLE IF NOT EXISTS Desktop
(
    u_id INTEGER REFERENCES NOT NULL (User.id) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER REFERENCES NOT NULL (Product.productID) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0)
    PRIMARY KEY (u_id, productID)
);

CREATE TABLE IF NOT EXISTS Animal
(
    u_id INTEGER REFERENCES NOT NULL (User.id) ON DELETE CASCADE ON UPDATE CASCADE,
    a_id INTEGER PRIMARY KEY,
    clean BOOLEAN,
    healthy BOOLEAN,
    age INTEGER,
    weight FLOAT,
    a_gender BOOL
);

CREATE TABLE IF NOT EXISTS Chicken
(
    a_id INTEGER PRIMARY KEY REFERENCES Animal(a_id) ON DELETE CASCADE ON UPDATE CASCADE,
    chicken_type ENUM,
    fasting BOOLEAN 
);

CREATE TABLE IF NOT EXISTS Rabbit
(
    a_id INTEGER PRIMARY KEY REFERENCES Animal(a_id) ON DELETE CASCADE ON UPDATE CASCADE,
    rabbit_type ENUM
);

CREATE TABLE IF NOT EXISTS Cow
(
    a_id INTEGER PRIMARY KEY  REFERENCES Animal(a_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Product
(
    productID INTEGER PRIMARY KEY,
    description TEXT,
    collection BOOLEAN,
    price FLOAT
);

CREATE TABLE IF NOT EXISTS Event
(
    e_id INTEGER PRIMARY KEY,          
    u_id INTEGER NOT NULL REFERENCES User(u_id) ON DELETE CASCADE ON UPDATE CASCADE,
    text VARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS User
(
    u_id INTEGER PRIMARY KEY,
    nom VARCHAR(20),
    sexe VARCHAR(20),
    ecus INTEGER,
    level INTEGER
);

CREATE TABLE IF NOT EXISTS Market
(
    u_id INTEGER NOT NULL REFERENCES (User.id) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES (Product.productID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Cooperative
(
    u_id INTEGER NOT NULL REFERENCES (User.id) ON DELETE CASCADE ON UPDATE CASCADE,
    productID INTEGER NOT NULL REFERENCES (Product.productID) ON DELETE CASCADE ON UPDATE CASCADE,
    is_open BOOLEAN
);
