CREATE TABLE IF NOT EXISTS "user" (
    uid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(20) CHECK (gender IN ('M', 'F')),
    ecus INTEGER,
    hibernation BOOLEAN DEFAULT FALSE,
    hibernation_date TIMESTAMP,
    level INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS product (
    product_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description TEXT,
    collection BOOLEAN,
    price FLOAT,
    coef INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS transaction (
    tid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seller INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    buyer INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    product INTEGER NOT NULL REFERENCES product (product_id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    total_price FLOAT NOT NULL CHECK (total_price >= 0),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (seller != buyer)
);

CREATE TABLE IF NOT EXISTS stock (
    uid INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product (product_id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity INTEGER DEFAULT 0 CHECK (quantity >= 0),
    collectible BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (uid, product_id)
);

CREATE TABLE IF NOT EXISTS animal (
    aid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uid INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    clean BOOLEAN DEFAULT TRUE,
    healthy BOOLEAN DEFAULT TRUE,
    age INTEGER,
    weight FLOAT,
    fed_today BOOLEAN DEFAULT FALSE,
    watered_today BOOLEAN DEFAULT FALSE,
    gender VARCHAR(20) CHECK (gender IN ('M', 'F'))
);

CREATE TABLE IF NOT EXISTS chicken (
    aid INTEGER PRIMARY KEY REFERENCES animal (aid) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR(50),
    chicken_type VARCHAR(20) CHECK (chicken_type IN ('C', 'H', 'R', 'L', 'B')),
    fasting BOOLEAN DEFAULT FALSE,
    fasting_days INTEGER,
    sick_days INTEGER
);

CREATE TABLE IF NOT EXISTS rabbit (
    aid INTEGER PRIMARY KEY REFERENCES animal (aid) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR(50),
    rabbit_type VARCHAR(20) CHECK (rabbit_type IN ('lapereau', 'lapin'))
);

CREATE TABLE IF NOT EXISTS cow (
    aid INTEGER PRIMARY KEY REFERENCES animal (aid) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR(50),
    cow_type VARCHAR(20) CHECK (cow_type IN ('D', 'C')),
    milking BOOLEAN DEFAULT FALSE,
    milk INTEGER DEFAULT 0,
    hay_today BOOLEAN DEFAULT FALSE,
    sick_days INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS event (
    eid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uid INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    text VARCHAR(200) NOT NULL,
    event_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market (
    uid INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product (product_id) ON DELETE CASCADE ON UPDATE CASCADE,
    price FLOAT NOT NULL,
    quantity INTEGER,
    PRIMARY KEY (uid, product_id)
);

CREATE TABLE IF NOT EXISTS cooperative (
    uid INTEGER NOT NULL REFERENCES "user" (uid) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product (product_id) ON DELETE CASCADE ON UPDATE CASCADE,
    is_open BOOLEAN,
    PRIMARY KEY (uid, product_id)
);