spring.application.name=tinyfarm
spring.datasource.url=jdbc:postgresql://postgres:5432/tinyfarm
spring.datasource.username=${DB_USERNAME_FILE}
spring.datasource.password=${DB_PASSWORD_FILE}

spring.jpa.hibernate.ddl-auto=validate
