spring.application.name=tinyfarm
secrets.username-path=./docker/secrets/db_username.txt
secrets.password-path=./docker/secrets/db_password.txt

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=./docker/secrets/db_username.txt
spring.datasource.password=./docker/secrets/db_password.txt

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect