spring.application.name=tinyfarm

spring.datasource.url=jdbc:postgresql://postgres:5432/tinyfarm
spring.datasource.username=@db.username@
spring.datasource.password=@db.password@

spring.profiles.active=prod
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=@jwt.secret@